/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as BuyDataRouteImport } from './routes/buy-data'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAccountApiKeysRouteImport } from './routes/_authenticated/account.api-keys'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated/admin.agents'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin.api-keys'
import { Route as AuthenticatedAdminBundlesRouteImport } from './routes/_authenticated/admin.bundles'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin.withdrawals'
import { Route as ApiPublicV1BundlesRouteImport } from './routes/api/public/v1/bundles'
import { Route as ApiPublicV1OrdersRouteImport } from './routes/api/public/v1/orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyDataRoute = BuyDataRouteImport.update({
  id: '/buy-data',
  path: '/buy-data',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAccountApiKeysRoute =
  AuthenticatedAccountApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBundlesRoute =
  AuthenticatedAdminBundlesRouteImport.update({
    id: '/bundles',
    path: '/bundles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1BundlesRoute = ApiPublicV1BundlesRouteImport.update({
  id: '/api/public/v1/bundles',
  path: '/api/public/v1/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrdersRoute = ApiPublicV1OrdersRouteImport.update({
  id: '/api/public/v1/orders',
  path: '/api/public/v1/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/bulk': typeof BulkRoute
  '/buy-data': typeof BuyDataRoute
  '/checkout': typeof CheckoutRoute
  '/developers': typeof DevelopersRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/support': typeof SupportRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agent': typeof AuthenticatedAgentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/account/api-keys': typeof AuthenticatedAccountApiKeysRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/bundles': typeof AuthenticatedAdminBundlesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/v1/bundles': typeof ApiPublicV1BundlesRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/bulk': typeof BulkRoute
  '/buy-data': typeof BuyDataRoute
  '/checkout': typeof CheckoutRoute
  '/developers': typeof DevelopersRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/support': typeof SupportRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/agent': typeof AuthenticatedAgentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/account/api-keys': typeof AuthenticatedAccountApiKeysRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/bundles': typeof AuthenticatedAdminBundlesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/v1/bundles': typeof ApiPublicV1BundlesRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/bulk': typeof BulkRoute
  '/buy-data': typeof BuyDataRoute
  '/checkout': typeof CheckoutRoute
  '/developers': typeof DevelopersRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/support': typeof SupportRoute
  '/track-order': typeof TrackOrderRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/_authenticated/account/api-keys': typeof AuthenticatedAccountApiKeysRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/bundles': typeof AuthenticatedAdminBundlesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/v1/bundles': typeof ApiPublicV1BundlesRoute
  '/api/public/v1/orders': typeof ApiPublicV1OrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/bulk'
    | '/buy-data'
    | '/checkout'
    | '/developers'
    | '/faq'
    | '/reviews'
    | '/support'
    | '/track-order'
    | '/account'
    | '/admin'
    | '/agent'
    | '/blog/$slug'
    | '/account/api-keys'
    | '/admin/agents'
    | '/admin/api-keys'
    | '/admin/bundles'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/admin/'
    | '/api/public/v1/bundles'
    | '/api/public/v1/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/bulk'
    | '/buy-data'
    | '/checkout'
    | '/developers'
    | '/faq'
    | '/reviews'
    | '/support'
    | '/track-order'
    | '/account'
    | '/agent'
    | '/blog/$slug'
    | '/account/api-keys'
    | '/admin/agents'
    | '/admin/api-keys'
    | '/admin/bundles'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/admin'
    | '/api/public/v1/bundles'
    | '/api/public/v1/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/bulk'
    | '/buy-data'
    | '/checkout'
    | '/developers'
    | '/faq'
    | '/reviews'
    | '/support'
    | '/track-order'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/agent'
    | '/blog/$slug'
    | '/_authenticated/account/api-keys'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/bundles'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/admin/'
    | '/api/public/v1/bundles'
    | '/api/public/v1/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BulkRoute: typeof BulkRoute
  BuyDataRoute: typeof BuyDataRoute
  CheckoutRoute: typeof CheckoutRoute
  DevelopersRoute: typeof DevelopersRoute
  FaqRoute: typeof FaqRoute
  ReviewsRoute: typeof ReviewsRoute
  SupportRoute: typeof SupportRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ApiPublicV1BundlesRoute: typeof ApiPublicV1BundlesRoute
  ApiPublicV1OrdersRoute: typeof ApiPublicV1OrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-data': {
      id: '/buy-data'
      path: '/buy-data'
      fullPath: '/buy-data'
      preLoaderRoute: typeof BuyDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/account/api-keys': {
      id: '/_authenticated/account/api-keys'
      path: '/api-keys'
      fullPath: '/account/api-keys'
      preLoaderRoute: typeof AuthenticatedAccountApiKeysRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bundles': {
      id: '/_authenticated/admin/bundles'
      path: '/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AuthenticatedAdminBundlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/bundles': {
      id: '/api/public/v1/bundles'
      path: '/api/public/v1/bundles'
      fullPath: '/api/public/v1/bundles'
      preLoaderRoute: typeof ApiPublicV1BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orders': {
      id: '/api/public/v1/orders'
      path: '/api/public/v1/orders'
      fullPath: '/api/public/v1/orders'
      preLoaderRoute: typeof ApiPublicV1OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountApiKeysRoute: typeof AuthenticatedAccountApiKeysRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountApiKeysRoute: AuthenticatedAccountApiKeysRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminBundlesRoute: typeof AuthenticatedAdminBundlesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminBundlesRoute: AuthenticatedAdminBundlesRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BulkRoute: BulkRoute,
  BuyDataRoute: BuyDataRoute,
  CheckoutRoute: CheckoutRoute,
  DevelopersRoute: DevelopersRoute,
  FaqRoute: FaqRoute,
  ReviewsRoute: ReviewsRoute,
  SupportRoute: SupportRoute,
  TrackOrderRoute: TrackOrderRoute,
  ApiPublicV1BundlesRoute: ApiPublicV1BundlesRoute,
  ApiPublicV1OrdersRoute: ApiPublicV1OrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
